// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Klaviyo init script */}
        <Script id="klaviyo-init" strategy="beforeInteractive">
          {`
            !function(){if(!window.klaviyo){window._klOnsite=window._klOnsite||[];
            try{window.klaviyo=new Proxy({},{
              get:function(t,e){return"push"===e?function(){
              var t;return(t=window._klOnsite).push.apply(t,arguments)}:void 0}})
            }catch(t){window.klaviyo=window.klaviyo||[],
            window.klaviyo.push=function(){var t;
            return(t=window._klOnsite).push.apply(t,arguments)}}}}();
          `}
        </Script>

        {/* Klaviyo main script */}
        <Script
          strategy="afterInteractive"
          src="https://static.klaviyo.com/onsite/js/klaviyo.js?company_id=YOUR_PUBLIC_API_KEY"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
